# Unique identifier for your project in SonarQube
sonar.projectKey=BlazorHelloWorld

# Name displayed in the SonarQube UI
sonar.projectName=BlazorHelloWorld

# Comma-separated paths to directories containing source code
sonar.sources=Components
