apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpbaceria-app
  labels:
    app: gpbaceria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpbaceria
  template:
    metadata:
      labels:
        app: gpbaceria
    spec:
      containers:
      - name: web-server
        image: 295934382080.dkr.ecr.us-east-1.amazonaws.com/gpbaceria:5df144ea97a5b874d20a3746d0222390434569d1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gpbaceria-service
spec:
  type: LoadBalancer
  selector:
    app: gpbaceria
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
