#Pipeline CI / CD
name: Pipeline CI / CD

on:
# push:
#   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: CI
    runs-on: ubuntu-latest

    steps:
    # paso 1: se hace checkout del código fuente del repositorio
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Required by SonarQube for better analysis relevance

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0' # Change to '9.0.x' or your specific .NET version

    # paso 2: se ejecutan las pruebas unitarias y se construye la solución
    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run bUnit Tests
      run: dotnet test --no-build --verbosity normal

    
    # Paso 3: Scan the raw source code using SonarQube
    #- name: SonarQube Scan
    #  uses: sonarsource/sonarqube-scan-action@v4
    #  env:
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Remove if using SonarCloud
      
      # Optional: Force the workflow to fail if SonarQube Quality Gate fails
      # with:
      #   args: >
      #     -Dsonar.qualitygate.wait=true

    # Paso 4: Configura Credenciales AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Paso 5: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Paso 6: Build Docker Image locally
    - name: Build Docker Image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .

    # Paso 7: Escanear con Trivy para buscar vulnerabilidades en la imagen Docker
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'

    # Paso 8: Push to ECR only if both SonarQube and Trivy checks pass
    - name: Push Image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gpbaceria
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        echo "Image pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"


    # Paso 9: Conectar al cluster de kubernetes
    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --name eks-aceria-east1 --region us-east-1

    # Paso 10: Set up kubectl CLI
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v4

    # Paso 11: Apply Kubernetes Manifests and update image dynamically
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment.app/gpbaceria-app web-server=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        kubectl rollout restart deployment.app/gpbaceria-app


#Run sed -i "s|IMAGE_PLACEHOLDER|295934382080.dkr.ecr.us-east-1.amazonaws.com/***:f0bb37f197d7c151a7f2000405abd63f2060cb18|g" k8s/otro.yaml
#Run sed -i "s|IMAGE_PLACEHOLDER|295934382080.dkr.ecr.us-east-1.amazonaws.com/***:f0bb37f197d7c151a7f2000405abd63f2060cb18|g" k8s/otro.yaml
#deployment.apps/my-world-app unchanged
#service/my-world-service unchanged
#kubectl set image deployment.app/gpbaceria-app web-server=nginx:latest
#kubectl set image deployment.app/gpbaceria-app web-server=295934382080.dkr.ecr.us-east-1.amazonaws.com/gpbaceria:latest
